#!/bin/bash

# https://askubuntu.com/questions/65764/how-do-i-toggle-sound-with-amixer

CURRENT_STATE=`amixer get Master | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]'`

if [[ $CURRENT_STATE == '[on]' ]]; then
    amixer set Master mute      | tail -n 1 | cut -d ' ' -f 6-10
else
    amixer set Master unmute    | tail -n 1 | cut -d ' ' -f 6-10
    amixer set Headphone unmute | tail -n 1 | cut -d ' ' -f 6-10 >/dev/null
    amixer set Speaker unmute   | tail -n 1 | cut -d ' ' -f 6-10 >/dev/null
fi
